services:
  - type: web
    name: gmail-trustworthy-classifier
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=10000 --server.enableCORS=false"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
